prism:
  algorithm:
    executions: 30

machine:
  cpu:
    cores: 8 

jmx:
  server:
    host: localhost
    port: 8081

spring:
  profiles:
    active: absolute 

logging:
  level:
    root: info
    pt.base.incubator: debug 

    